#!/usr/bin/env bash

log() {
    echo -e "\e[35m :: $*\e[0m"
}

# Make sure the Android device is connected
assert_device_connected() {
    if [[ -z "$(adb devices -l | tail -n +2)" ]]
    then
        err "Android device not connected"
        exit 1
    fi
}

pull() {
    local pkgs
    local tmp
    local paths

    pkgs="$(adb shell pm list packages -3 | sed 's/package://')"
    for pkg_id in $pkgs
    do
        log "Fetching $pkg_id..."
        tmp="$(mktemp -d)"
        paths="$(adb shell pm path "$pkg_id" | sed 's/package://')"
        
        # Be extra safe in case of a force exit
        # Get everything we need, then overwrite
        for path in $paths
        do
            adb pull "$path" "$tmp/"
        done

        # Get OBB if it exists
        obb="/storage/self/primary/Android/obb/$pkg_id"
        if adb shell "[[ -d $obb ]]"
        then
            mkdir -p "$tmp/obb/"
            adb pull "$obb" "$tmp/obb/"
        fi
        
        # Okay, now overwrite
        rm -rf "$pkg_id"
        mkdir -p "$pkg_id"
        mv "$tmp"/* "$pkg_id/"
        rm -rf "$tmp"

        echo
    done
}

assert_device_connected
pull